packages:
  - apps/*
  - packages/*

catalog:
  '@prisma/client': ^7.2.0
  '@tanstack/react-query': ^5.90.12
  dotenv: ^17.2.2
  typescript: ^5
  zod: ^4.1.13

patchedDependencies:
  '@expo/metro-runtime@6.1.2': patches/@expo__metro-runtime@6.1.2.patch
