"use strict";
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeTree = void 0;
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
var __root_1 = require("./routes/__root");
var import_1 = require("./routes/import");
var audit_1 = require("./routes/audit");
var index_1 = require("./routes/index");
var events__eventId_1 = require("./routes/events.$eventId");
var ImportRoute = import_1.Route.update({
    id: '/import',
    path: '/import',
    getParentRoute: function () { return __root_1.Route; },
});
var AuditRoute = audit_1.Route.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: function () { return __root_1.Route; },
});
var IndexRoute = index_1.Route.update({
    id: '/',
    path: '/',
    getParentRoute: function () { return __root_1.Route; },
});
var EventsEventIdRoute = events__eventId_1.Route.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: function () { return __root_1.Route; },
});
var rootRouteChildren = {
    IndexRoute: IndexRoute,
    AuditRoute: AuditRoute,
    ImportRoute: ImportRoute,
    EventsEventIdRoute: EventsEventIdRoute,
};
exports.routeTree = __root_1.Route
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
